### ISSUE TITLE
Missing @connected_comp prevents writing XGMML

### ISSUE THREAD

**Issue by clairemerot** [CMPG/signet#1]
I 'am using the signet package at the moment and I really like it, it is super interesting and works well: thanks for building it!
I am stuck because I am not able to visualise the output with the WGMML function. In fact, when running the signet process (searchSubnet) or (searchSubnet + nullDist + testSubnet), the output (even with the example database daub13) never contains anything in the HSS@connected_comp.

Formal class 'SignetList' [package "signet"] with 1 slot
  ..@ results:List of 3
  .. ..$ Acute myeloid leukemia         :Formal class 'Signet' [package "signet"] with 9 slots
  .. .. .. ..@ connected_comp : 'graphNEL' logi NA

This results in an error when trying writeXGMML which arises at the early steps ( graph::edges(sigObj@connected_comp)[[i]] )
> writeXGMML(example[[1]])
Error in .local(object, which, ...) : 
  tentative d'obtenir le slot "nodes" d'un objet (classe "graphNEL") qui n'est pas un objet S4

Any idea about how to fix that?
Thanks a lot
Claire

**Comment by agouy** [comment]
Hi Claire,
Thanks for using signet and reporting this issue! I'll investigate in the next few days and get back to you as soon as I have an answer.

**Comment by clairemerot** [comment]
Hi Alexander,
I am sorry I should have closed the issue or let you know that I found a way around. It may not be the cleanest but seems to be doing fine:

First, I modified the function SearchSubnet (inspired by older copies of your repository that were producing xgmml output) and I removed lines 88-92:
```
else {
                na.gr <- NA
                class(na.gr) <- "graphNEL"
                res@connected_comp <- na.gr
            }
```
as well as line 94 ``` gc() ```

But then, it runs into an error when the pathways were empty. So before running signet, I clean the pathway db with a few lines in R:
```
paths_droso <- pathways("dmelanogaster", "kegg")
pathway_droso <- lapply(paths_droso, pathwayGraph) #apply the conversion to graph to the list of "pathways" object (graphNEL graph)
#find which pathways are empty (this is to remove the empty pathways that make a bug)
dim_pathway<-vector(length=length(pathway_droso))
for (i in 1:length(pathway_droso))
{ 
dim_pathway[i]<-length(pathway_droso[[i]]@edgeL)
}
#keep only pathways which have information in edgeL
pathway_droso_ok <- lapply(paths_droso[dim_pathway>0], pathwayGraph) #apply the conversion to graph to the list of "pathways" object (graphNEL graph)
```

Thanks a lot for providing signet and supporting :-) I have another question but it should likely make another thematic issue.
Cheers
Claire

**Comment by tkchafin** [comment]
Merged pull request should fix this (https://github.com/CMPG/signet/pull/3)

**Comment by agouy** [comment]
Excellent, thanks.
